99999999999 = """## We'll be right back!
We are currently taking a quick ad break. The war will resume shortly!"""

44 = """## Welcome back!
Before we jump back in, let's take a quick look at the score..."""

30 = """## [SCORE_WIDGET]
Currently, [STINKY_HACK]"""

10 = "**Sit back and relax, as we return to the [COUNT_FANCY] Elden Towers War!**"
