44 = """## Carnage is brewing...
In less than a minute, the **[COUNT_FANCY] Elden Towers War** will begin, with the **[ATTACKING_TOWER]** facing off against the **[DEFENDING_TOWER]**!
*Here's what you need to know...*"""

36 = """The **[ATTACKING_TOWER]** is attempting to claim **[LOCATION_NAME]** from the **[DEFENDING_TOWER]**, and in order to settle the claim, **both towers have decided to go to war**.

Both towers have their own roster of fighters, who will be called up one by one by their strategist, who at the end of it all, will be the final fighter for their tower.
**The first tower to eliminate the other strategist or eliminate the area boss of [LOCATION_NAME] will win the war!**

Both towers and each fighter can purchase various perks throughout the war, which are detailed on the [war code](<https://docs.google.com/document/d/1IATFoyWEIdJ0UVl-GSRz8co2VWeK8QVTRJHMB0sKdJ8/view?tab=t.0#heading=h.brjnb6o4b6mj>)."""

10 = "**Get ready, the main event is starting!**"
